# Generated by Django 5.0.3 on 2024-04-03 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionDrink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_of_drink', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceDrink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_drink', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('temperature', models.CharField(choices=[('H', 'Hot Only'), ('I', 'Ice Only'), ('B', 'Both hot and ice')], default='B', max_length=1)),
                ('chosen_drink_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.questiondrink')),
            ],
        ),
    ]
