# Generated by Django 5.0.3 on 2024-04-05 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceDrink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_drink', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('temperature', models.CharField(choices=[('H', 'Hot Only'), ('I', 'Ice Only'), ('B', 'Both hot and ice')], default='B', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionDrink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_of_drink', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('order_item_count', models.IntegerField()),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order_item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.choicedrink')),
            ],
        ),
        migrations.AddField(
            model_name='choicedrink',
            name='chosen_drink_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.questiondrink'),
        ),
    ]
